POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "user2@user.com",
    "password": "123456"
}

###
// informando o token, não expirado - exibe detalhes da requisição usando Req()
GET http://localhost:3000/test-auth2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoidXNlcjJAdXNlci5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTYzMTgyNzMzMiwiZXhwIjoxNjMxODI3NjMyfQ.rv14NPJUnmi0tg9hiyjp7Md4KezEr89bbBRvKrt656c


###
//Tentando acessar sem token, o guard impede
GET http://localhost:3000/test-auth

###
// informando o token, não expirado
GET http://localhost:3000/test-auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoidXNlcjFAdXNlci5jb20iLCJpYXQiOjE2MzE3NTc4MTMsImV4cCI6MTYzMTc1Nzg3M30.tISEFxrhwTJwiVej8zPtxMyoIdGXshYFpmmGJI8JlQA

###
GET http://localhost:3000/exemplo

###
GET http://localhost:3000/teste