#antes de executar, dar permissao:  chmod +x entrypoint.sh
version: '3'

services: 
  app:
    build: .
    entrypoint: ./entrypoint.sh
    ports: 
      - 3000:3000
    volumes: 
      - .:/home/node/app
    #extra_hosts: 
      #- "kafka:172.23.0.3"
      #      - "host.docker.internal:172.17.0.1"

#   ^ para comunicar com o kafka incluir
#    extra_hosts: 
#      -  "host.docker.internal:172.17.0.1"  - que é o gateway padrao da rede do docker 
#
#    a chamada a host.docker.internal:9094 -> vai ser desviada para 172.17.0.1 que é o gateway 
#       que vai ser redirecionado para o localhost 127.0.0.1 (por causa do arquivo hosts do windows)
#       que é onde o listener da porta 9094 está

networks:
  default:
    external: true
    name: my-network