version: '3'

services: 
  app:
    build: .
    entrypoint: ./entrypoint.sh
    ports: 
      - 3000:3000
    volumes: 
      - .:/home/node/app


#antes de executar, dar permissao:  chmod +x entrypoint.sh
